@startuml
actor Bob as b
participant "Protector (NFT)" as n
participant "TransparentSafeBox (NFT)" as v
participant "6551 Registry" as r
participant "Bound account" as w
participant "Wallet" as wi
actor Alice as a

note across #DDEEFF : Vault setup
    b -> v : Activate vault for protectorId 5
    v -> n : Ask for protector.ownerOf(5)
    n -> v : Return Bob address
    note over v
    The vault mints a new Vault token (vaultId)
    onwed by the vault contract itself.
    end note
    v -> r :Trigger createAccount to\ngenerate a new bound\naccount owned by vaultId
    r -> w : Deploy the new proxy
    note over w: Uses the wallet as implementation
    wi -> w : Wallet is initialized
    note over v, r
    Since the vault is the owner of vaultId,
    the vault has full control over the new account.
    end note

note across #DDEEFF: Deposit an asset
    b -> v : Deposit 1000 DAI
    v -> b : Ask for approval
    b -> v : Approve 1000 DAI
    note over v
    Saves info about the deposit
    end note
    v -> w : Transfer 1000 DAI from Bob's wallet\nto the bound account
    note over wi
    Verify that the tokens
    can be received
    end note
    wi -> w : Confirm the reception
    note over v : Emits events

note across #DDEEFF: Withdraw an asset
    b -> v : Withdraw 1000 DAI to be send to Alice
    note over v: Saves info about the withdrawal\nand emits events
    v -> w : Require the bound account to send\n1000 DAI to the beneficiary
    w -> a : Transfer 1000 DAI



@enduml
