#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# to skip it call git commit with HUSKY=0 git commit ...
if [[ "$HUSKY" != "0" ]]; then
 npm run lint && bin/get-coverage.sh && bin/export.sh && git add -A
fi

